export const TRIGGER_VERIFY_EMAIL_MODAL = "TRIGGER_VERIFY_EMAIL_MODAL";
export const TRIGGER_VERIFY_EMAIL_MODAL_SUCCESS =
  "TRIGGER_VERIFY_EMAIL_MODAL_SUCCESS";
export const TRIGGER_VERIFY_EMAIL_MODAL_FAILURE =
  "TRIGGER_VERIFY_EMAIL_MODAL_FAILURE";
